services:
  # Combined Backend + Frontend Service
  - type: web
    name: timetable-app
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
    healthCheckPath: /api/health
